// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package igg_reporter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	SnId                 int64    `protobuf:"varint,1,opt,name=snId,proto3" json:"snId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Os                   string   `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	AppVersion           string   `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Time                 int64    `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Website              string   `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	ConnectTime          int64    `protobuf:"varint,9,opt,name=connectTime,proto3" json:"connectTime,omitempty"`
	Rate                 int64    `protobuf:"varint,10,opt,name=rate,proto3" json:"rate,omitempty"`
	Traffic              int64    `protobuf:"varint,11,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CarrierOperator      string   `protobuf:"bytes,12,opt,name=carrierOperator,proto3" json:"carrierOperator,omitempty"`
	UserType             string   `protobuf:"bytes,13,opt,name=userType,proto3" json:"userType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_record_bb5bcf1446fec69b, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetSnId() int64 {
	if m != nil {
		return m.SnId
	}
	return 0
}

func (m *Record) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Record) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Record) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Record) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Record) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Record) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Record) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Record) GetConnectTime() int64 {
	if m != nil {
		return m.ConnectTime
	}
	return 0
}

func (m *Record) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Record) GetTraffic() int64 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *Record) GetCarrierOperator() string {
	if m != nil {
		return m.CarrierOperator
	}
	return ""
}

func (m *Record) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func init() {
	proto.RegisterType((*Record)(nil), "igg.reporter.Record")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_record_bb5bcf1446fec69b) }

var fileDescriptor_record_bb5bcf1446fec69b = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xf3, 0x30,
	0x10, 0x84, 0x95, 0xb4, 0x7f, 0xda, 0x6e, 0xf3, 0x83, 0xb4, 0x07, 0xb4, 0xe2, 0x80, 0x22, 0x4e,
	0x39, 0xf5, 0xc2, 0x53, 0xe4, 0x84, 0x14, 0x55, 0xdc, 0x5d, 0x7b, 0x5b, 0xf9, 0x40, 0x6c, 0xad,
	0x0d, 0x88, 0xf7, 0xe4, 0x81, 0x90, 0x37, 0x04, 0x55, 0xdc, 0x76, 0x3e, 0xcf, 0x8e, 0x57, 0x03,
	0xad, 0xb0, 0x0d, 0xe2, 0x0e, 0x51, 0x42, 0x0e, 0xd8, 0xfa, 0xcb, 0xe5, 0x20, 0x1c, 0x83, 0x64,
	0x96, 0xc7, 0xaf, 0x1a, 0x9a, 0x51, 0x9f, 0x11, 0x61, 0x9d, 0xa6, 0xc1, 0x51, 0xd5, 0x55, 0xfd,
	0x6a, 0xd4, 0x19, 0xef, 0xa0, 0x79, 0x4b, 0x2c, 0x83, 0xa3, 0x5a, 0xe9, 0x8f, 0xc2, 0x7b, 0xd8,
	0x3a, 0x7e, 0xf7, 0x96, 0x07, 0x47, 0xab, 0xae, 0xea, 0x77, 0xe3, 0xaf, 0xc6, 0x1b, 0xa8, 0x43,
	0xa2, 0xb5, 0xd2, 0x3a, 0x24, 0x7c, 0x00, 0x30, 0x31, 0xbe, 0xb0, 0x24, 0x1f, 0x26, 0xfa, 0xa7,
	0xfc, 0x8a, 0x14, 0xbf, 0x8f, 0xd4, 0xcc, 0x7e, 0x1f, 0xcb, 0x1d, 0xd9, 0xbf, 0x32, 0x6d, 0xe6,
	0x3b, 0xca, 0x8c, 0x04, 0x9b, 0x0f, 0x3e, 0x25, 0x9f, 0x99, 0xb6, 0x6a, 0x5c, 0x24, 0x76, 0xb0,
	0xb7, 0x61, 0x9a, 0xd8, 0xe6, 0x63, 0x59, 0xda, 0xe9, 0xd2, 0x35, 0x2a, 0x79, 0x62, 0x32, 0x13,
	0xcc, 0x79, 0x65, 0x2e, 0x79, 0x59, 0xcc, 0xf9, 0xec, 0x2d, 0xed, 0x15, 0x2f, 0x12, 0x7b, 0xb8,
	0xb5, 0x46, 0xc4, 0xb3, 0x3c, 0x47, 0x16, 0x93, 0x83, 0x50, 0xab, 0x3f, 0xfe, 0xc5, 0xa5, 0x83,
	0xd2, 0xc6, 0xf1, 0x33, 0x32, 0xfd, 0x9f, 0x3b, 0x58, 0xf4, 0xa9, 0xd1, 0xae, 0x9f, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x21, 0x16, 0x37, 0xaf, 0x7b, 0x01, 0x00, 0x00,
}
