// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package igg_reporter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	SnId                 int64    `protobuf:"varint,1,opt,name=snId,proto3" json:"snId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Os                   string   `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	AppVersion           string   `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Time                 int64    `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Website              string   `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	ConnectTime          int64    `protobuf:"varint,9,opt,name=connectTime,proto3" json:"connectTime,omitempty"`
	Rate                 int64    `protobuf:"varint,10,opt,name=rate,proto3" json:"rate,omitempty"`
	Traffic              int64    `protobuf:"varint,11,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CarrierOperator      string   `protobuf:"bytes,12,opt,name=carrierOperator,proto3" json:"carrierOperator,omitempty"`
	UserType             string   `protobuf:"bytes,13,opt,name=userType,proto3" json:"userType,omitempty"`
	AppId                int64    `protobuf:"varint,14,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetSnId() int64 {
	if m != nil {
		return m.SnId
	}
	return 0
}

func (m *Record) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Record) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Record) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Record) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Record) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Record) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Record) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Record) GetConnectTime() int64 {
	if m != nil {
		return m.ConnectTime
	}
	return 0
}

func (m *Record) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Record) GetTraffic() int64 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

func (m *Record) GetCarrierOperator() string {
	if m != nil {
		return m.CarrierOperator
	}
	return ""
}

func (m *Record) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *Record) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "igg.reporter.Record")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x6a, 0xf3, 0x30,
	0x10, 0x84, 0x89, 0x93, 0x38, 0xc9, 0x26, 0x7f, 0x7e, 0x10, 0xb4, 0x2c, 0x3d, 0x14, 0xd3, 0x93,
	0x4f, 0xb9, 0xf4, 0x29, 0x7c, 0x2a, 0x98, 0xd0, 0x6b, 0x51, 0xa4, 0x4d, 0xd0, 0xa1, 0xd6, 0xb2,
	0x52, 0x5b, 0xfa, 0xcc, 0x7d, 0x89, 0xa2, 0x75, 0x5d, 0x42, 0x6f, 0x3b, 0x9f, 0x67, 0xc7, 0xcb,
	0x08, 0x76, 0x42, 0x2e, 0x8a, 0x3f, 0xb0, 0xc4, 0x1c, 0xcd, 0x2e, 0x5c, 0x2e, 0x07, 0x21, 0x8e,
	0x92, 0x49, 0x1e, 0xbe, 0x2a, 0xa8, 0x7b, 0xfd, 0x6c, 0x0c, 0x2c, 0xd2, 0xd0, 0x79, 0x9c, 0x35,
	0xb3, 0x76, 0xde, 0xeb, 0x6c, 0x6e, 0xa1, 0x7e, 0x4b, 0x24, 0x9d, 0xc7, 0x4a, 0xe9, 0x8f, 0x32,
	0x77, 0xb0, 0xf6, 0xf4, 0x1e, 0x1c, 0x75, 0x1e, 0xe7, 0xcd, 0xac, 0xdd, 0xf4, 0xbf, 0xda, 0xec,
	0xa1, 0x8a, 0x09, 0x17, 0x4a, 0xab, 0x98, 0xcc, 0x3d, 0x80, 0x65, 0x7e, 0x26, 0x49, 0x21, 0x0e,
	0xb8, 0x54, 0x7e, 0x45, 0x8a, 0x3f, 0x30, 0xd6, 0xa3, 0x3f, 0x70, 0xb9, 0x23, 0x87, 0x57, 0xc2,
	0xd5, 0x78, 0x47, 0x99, 0x0d, 0xc2, 0xea, 0x83, 0x4e, 0x29, 0x64, 0xc2, 0xb5, 0x1a, 0x27, 0x69,
	0x1a, 0xd8, 0xba, 0x38, 0x0c, 0xe4, 0xf2, 0xb1, 0x2c, 0x6d, 0x74, 0xe9, 0x1a, 0x95, 0x3c, 0xb1,
	0x99, 0x10, 0xc6, 0xbc, 0x32, 0x97, 0xbc, 0x2c, 0xf6, 0x7c, 0x0e, 0x0e, 0xb7, 0x8a, 0x27, 0x69,
	0x5a, 0xf8, 0xef, 0xac, 0x48, 0x20, 0x79, 0x62, 0x12, 0x9b, 0xa3, 0xe0, 0x4e, 0xff, 0xf8, 0x17,
	0x97, 0x0e, 0x4a, 0x1b, 0xc7, 0x4f, 0x26, 0xfc, 0x37, 0x76, 0x30, 0x69, 0x73, 0x03, 0xb5, 0x65,
	0x7e, 0x09, 0x1e, 0xf7, 0x1a, 0xbf, 0xb4, 0xcc, 0x9d, 0x3f, 0xd5, 0xfa, 0x04, 0x8f, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0xbc, 0x98, 0xb8, 0x92, 0x01, 0x00, 0x00,
}
